In [325]:
# Library to interact with the OS
import os

# Libraries for reading and manipulating data
import numpy as np
import pandas as pd

# Libraries for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [327]:
df_train=pd.read_csv('augmented_train.csv')

In [329]:
df_train.head(2)

,Potential Accident Level,Gender,Country_Country_01,Country_Country_02,Country_Country_03,Local_Local_01,Local_Local_02,Local_Local_03,Local_Local_04,Local_Local_05,...,Critical Risk_Projection/Burning,Critical Risk_Projection/Choco,Critical Risk_Projection/Manual Tools,Critical Risk_Suspended Loads,Critical Risk_Traffic,Critical Risk_Vehicles and Mobile Equipment,Critical Risk_Venomous Animals,Critical Risk_remains of choco,Description,Accident Level
0,4,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,By manually moving a steel cabinet for disposa...,3
1,4,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,Once the mooring of the faneles in the detonat...,1

In [331]:
df_test=pd.read_csv('augmented_test.csv')

In [333]:
df_test.head(2)

,Potential Accident Level,Gender,Description,Country_Country_01,Country_Country_02,Country_Country_03,Local_Local_01,Local_Local_02,Local_Local_03,Local_Local_04,...,Critical Risk_Projection of fragments,Critical Risk_Projection/Burning,Critical Risk_Projection/Choco,Critical Risk_Projection/Manual Tools,Critical Risk_Suspended Loads,Critical Risk_Traffic,Critical Risk_Vehicles and Mobile Equipment,Critical Risk_Venomous Animals,Critical Risk_remains of choco,Accident Level
0,1,0,On 02/03/17 during the soil sampling in the re...,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,4,0,During execution of drilling on the target - B...,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3

In [335]:
df_test.columns

Index(['Potential Accident Level', 'Gender', 'Description',
       'Country_Country_01', 'Country_Country_02', 'Country_Country_03',
       'Local_Local_01', 'Local_Local_02', 'Local_Local_03', 'Local_Local_04',
       'Local_Local_05', 'Local_Local_06', 'Local_Local_07', 'Local_Local_08',
       'Local_Local_09', 'Local_Local_10', 'Local_Local_11', 'Local_Local_12',
       'Industry Sector_Metals', 'Industry Sector_Mining',
       'Industry Sector_Others', 'Employee or Third Party_Employee',
       'Employee or Third Party_Third Party',
       'Employee or Third Party_Third Party (Remote)',
       'Critical Risk_\nNot applicable', 'Critical Risk_Bees',
       'Critical Risk_Blocking and isolation of energies',
       'Critical Risk_Burn', 'Critical Risk_Chemical substances',
       'Critical Risk_Confined space', 'Critical Risk_Cut',
       'Critical Risk_Electrical Shock',
       'Critical Risk_Electrical installation', 'Critical Risk_Fall',
       'Critical Risk_Fall prevention',
       'Critical Risk_Fall prevention (same level)',
       'Critical Risk_Individual protection equipment',
       'Critical Risk_Liquid Metal', 'Critical Risk_Machine Protection',
       'Critical Risk_Manual Tools', 'Critical Risk_Others',
       'Critical Risk_Plates', 'Critical Risk_Poll',
       'Critical Risk_Power lock', 'Critical Risk_Pressed',
       'Critical Risk_Pressurized Systems',
       'Critical Risk_Pressurized Systems / Chemical Substances',
       'Critical Risk_Projection', 'Critical Risk_Projection of fragments',
       'Critical Risk_Projection/Burning', 'Critical Risk_Projection/Choco',
       'Critical Risk_Projection/Manual Tools',
       'Critical Risk_Suspended Loads', 'Critical Risk_Traffic',
       'Critical Risk_Vehicles and Mobile Equipment',
       'Critical Risk_Venomous Animals', 'Critical Risk_remains of choco',
       'Accident Level'],
      dtype='object')

In [339]:
df_test.head()

,Potential Accident Level,Gender,Description,Country_Country_01,Country_Country_02,Country_Country_03,Local_Local_01,Local_Local_02,Local_Local_03,Local_Local_04,...,Critical Risk_Projection of fragments,Critical Risk_Projection/Burning,Critical Risk_Projection/Choco,Critical Risk_Projection/Manual Tools,Critical Risk_Suspended Loads,Critical Risk_Traffic,Critical Risk_Vehicles and Mobile Equipment,Critical Risk_Venomous Animals,Critical Risk_remains of choco,Accident Level
0,1,0,On 02/03/17 during the soil sampling in the re...,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,4,0,During execution of drilling on the target - B...,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,3
2,3,0,"The operator was in the center (Demag IV), per...",0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,0,The employee was transiting toward the cadmium...,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,4,0,"Being 12:20 hours Approximately, in circumstan...",1,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,2

In [341]:
# to use regular expressions for manipulating text data
import re

# to load the natural language toolkit
import nltk
nltk.download('stopwords')    # loading the stopwords
nltk.download('wordnet')  

# to remove common stop words
from nltk.corpus import stopwords

# to perform stemming
from nltk.stem.porter import PorterStemmer

# to create Bag of Words
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [343]:
# Removing non-alphanumeric chars
df_train['Description_T'] = df_train['Description'].apply(lambda x: ''.join(re.sub('[^A-Za-z0-9]+', ' ', str(x))))
df_test['Description_T'] = df_test['Description'].apply(lambda x: ''.join(re.sub('[^A-Za-z0-9]+', ' ', str(x))))

In [345]:
#removing digits
df_train['Description_T'] = df_train['Description_T'].apply(lambda x: ''.join(re.sub(r'\d+',' ', str(x))))
df_test['Description_T'] = df_test['Description_T'].apply(lambda x: ''.join(re.sub(r'\d+',' ', str(x))))

In [347]:
# To lowercase
df_train['Description_T'] = df_train['Description_T'].apply(lambda x: str(x).lower())
df_test['Description_T'] = df_test['Description_T'].apply(lambda x: str(x).lower())

In [349]:
df_train['Description_T'] = df_train['Description_T'].str.strip()
df_test['Description_T'] = df_test['Description_T'].str.strip()

In [351]:
# Stopword removal
df_train['Description_T'] = df_train['Description_T'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))

# Stopword removal
df_test['Description_T'] = df_test['Description_T'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))

In [353]:
df_train.loc[0:10, ['Description', 'Description_T']]

,Description,Description_T
0,By manually moving a steel cabinet for disposa...,manually moving steel cabinet disposal help an...
1,Once the mooring of the faneles in the detonat...,mooring faneles detonating cord completed inju...
2,When performing cleaning activity of the area ...,performing cleaning activity area near tc grin...
3,The technician was doing the magnetometric sur...,technician magnetometric survey stepped thorn ...
4,The operator cleaned with spatula spear throug...,operator cleaned spatula spear one windows boi...
5,"On 02/25/2017 at 13:05 p.m., when assisting wi...",p assisting gps magnetometric collaborator gil...
6,"On 05/02/2017, at 10:40 p.m., when performing ...",p performing geological mapping activity geolo...
7,"In phase III of the concentrator plant, the ma...",phase iii concentrator plant maintenance perso...
8,"While preparing to mount polypropylene tubing,...",preparing mount polypropylene tubing employee ...
9,After the welder completed the welding work to...,welder completed welding work reinforce forms ...
10,The technician Operator when heading towards t...,technician operator heading towards zone lifti...

In [355]:
df_test.loc[0:10, ['Description', 'Description_T']]

,Description,Description_T
0,On 02/03/17 during the soil sampling in the re...,soil sampling region sta employees rafael dani...
1,During execution of drilling on the target - B...,execution drilling target bolt brjcldd made co...
2,"The operator was in the center (Demag IV), per...",operator center demag iv performing maintenanc...
3,The employee was transiting toward the cadmium...,employee transiting toward cadmium factory nea...
4,"Being 12:20 hours Approximately, in circumstan...",hours approximately circumstances administrati...
5,"At Rp 050 of level 1620, in circumstances wher...",rp level circumstances workers company perform...
6,When observing the pulp overflow of the overfl...,observing pulp overflow overflow reception dra...
7,During the execution of the soil sampling task...,execution soil sampling task potions area arou...
8,In moments that the truck of transport of pers...,moments truck transport personnel company mcei...
9,Employee moved toward the structure of post 10...,employee moved toward structure post came step...
10,The employees MÃ¡rcio and SÃ©rgio performed the ...,employees rcio rgio performed pump pipe cleari...

In [357]:
nltk.download('punkt')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
df_train['Description_WL'] = df_train.apply(lambda row: nltk.word_tokenize(row['Description_T']), axis=1)
def lemmatize_list(words):
    new_words = []
    for word in words:
      new_words.append(lemmatizer.lemmatize(word, pos='v'))
    return ' '.join(new_words)
df_train['Description_WL'] = df_train.apply(lambda x: lemmatize_list(x['Description_WL']), axis=1)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [359]:
df_train.loc[0:10, ['Description', 'Description_WL']]

,Description,Description_WL
0,By manually moving a steel cabinet for disposa...,manually move steel cabinet disposal help anot...
1,Once the mooring of the faneles in the detonat...,moor faneles detonate cord complete injure per...
2,When performing cleaning activity of the area ...,perform clean activity area near tc grind empl...
3,The technician was doing the magnetometric sur...,technician magnetometric survey step thorn rea...
4,The operator cleaned with spatula spear throug...,operator clean spatula spear one windows boile...
5,"On 02/25/2017 at 13:05 p.m., when assisting wi...",p assist gps magnetometric collaborator gilv n...
6,"On 05/02/2017, at 10:40 p.m., when performing ...",p perform geological map activity geologist ma...
7,"In phase III of the concentrator plant, the ma...",phase iii concentrator plant maintenance perso...
8,"While preparing to mount polypropylene tubing,...",prepare mount polypropylene tube employee pull...
9,After the welder completed the welding work to...,welder complete weld work reinforce form deepe...
10,The technician Operator when heading towards t...,technician operator head towards zone lift con...

In [361]:
nltk.download('punkt')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
df_test['Description_WL'] = df_test.apply(lambda row: nltk.word_tokenize(row['Description_T']), axis=1)
def lemmatize_list(words):
    new_words = []
    for word in words:
      new_words.append(lemmatizer.lemmatize(word, pos='v'))
    return ' '.join(new_words)
df_test['Description_WL'] = df_test.apply(lambda x: lemmatize_list(x['Description_WL']), axis=1)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [363]:
df_test.loc[0:10, ['Description', 'Description_WL']]

,Description,Description_WL
0,On 02/03/17 during the soil sampling in the re...,soil sample region sta employees rafael danill...
1,During execution of drilling on the target - B...,execution drill target bolt brjcldd make compa...
2,"The operator was in the center (Demag IV), per...",operator center demag iv perform maintenance t...
3,The employee was transiting toward the cadmium...,employee transit toward cadmium factory near t...
4,"Being 12:20 hours Approximately, in circumstan...",hours approximately circumstances administrati...
5,"At Rp 050 of level 1620, in circumstances wher...",rp level circumstances workers company perform...
6,When observing the pulp overflow of the overfl...,observe pulp overflow overflow reception drawe...
7,During the execution of the soil sampling task...,execution soil sample task potions area around...
8,In moments that the truck of transport of pers...,moments truck transport personnel company mcei...
9,Employee moved toward the structure of post 10...,employee move toward structure post come step ...
10,The employees MÃ¡rcio and SÃ©rgio performed the ...,employees rcio rgio perform pump pipe clear ac...

In [545]:
df_train1=df_train.copy()
df_test1=df_test.copy()

In [547]:
from nltk.tokenize import word_tokenize, RegexpTokenizer

# RegexpTokenizer
regexp = RegexpTokenizer("[\w']+")

In [549]:
# Text normalization for Word2Vec
for df in [df_train1,df_test1]:
    df['tokens'] = (df["Description_WL"].apply(regexp.tokenize))
df_train1[['tokens', 'Accident Level']]

                                                 tokens  Accident Level
0     [manually, move, steel, cabinet, disposal, hel...               3
1     [moor, faneles, detonate, cord, complete, inju...               1
2     [perform, clean, activity, area, near, tc, gri...               3
3     [technician, magnetometric, survey, step, thor...               1
4     [operator, clean, spatula, spear, one, windows...               1
...                                                 ...             ...
1150  [approximately, hours, routine, maintenance, o...               5
1151  [hours, routine, maintenance, operation, secto...               5
1152  [installation, activity, meter, diameter, vent...               5
1153  [maintenance, activity, conveyor, belt, feed, ...               5
1154  [maintenance, activity, conveyor, belt, feed, ...               5

[1155 rows x 2 columns]

In [551]:
from gensim.models import Word2Vec

In [553]:
# Loading the pre-trained Word2Vec model
word2vec_path = 'GoogleNews-vectors-negative300.bin'

In [555]:
# Loading the pre-trained Word2Vec model
word2vec_path = 'GoogleNews-vectors-negative300.bin'
word2vec = gensim.models.KeyedVectors.load_word2vec_format('GoogleNews-vectors-negative300.bin', binary=True)

In [557]:
# Some useful functions for Word2Vec
def get_average_word2vec(tokens_list, vector, generate_missing = False, k = 300):
    if len(tokens_list) < 1:
        return np.zeros(k)
    if generate_missing:
        vectorized = [vector[word] if word in vector else np.random.rand(k) for word in tokens_list]
    else:
        vectorized = [vector[word] if word in vector else np.zeros(k) for word in tokens_list]
    length = len(vectorized)
    summed = np.sum(vectorized, axis = 0)
    averaged = np.divide(summed, length)
    return averaged

def get_word2vec_embeddings(vectors, tokens, generate_missing = False):
    embeddings = tokens.apply(lambda x: get_average_word2vec(x, vectors, generate_missing = generate_missing))
    return list(embeddings)

In [559]:
# Word2Vec embedding
df_train_embed = get_word2vec_embeddings(word2vec, df_train1['tokens'])
df_test_embed = get_word2vec_embeddings(word2vec, df_test1['tokens'])

In [561]:
import scipy
from scipy import sparse
from scipy.sparse import csr_matrix

In [563]:
df_train_w2v = scipy.sparse.csr_matrix(df_train_embed)
df_test_w2v = scipy.sparse.csr_matrix(df_test_embed )

In [565]:
W2Vec_Data_train=pd.DataFrame(df_train_w2v.todense(), columns=['Word2vec_'+str(i) for i in range(300)])
W2Vec_Data_test=pd.DataFrame(df_test_w2v.todense(), columns=['Word2vec_'+str(i) for i in range(300)])

In [567]:
W2Vec_Data_train.head()

,Word2vec_0,Word2vec_1,Word2vec_2,Word2vec_3,Word2vec_4,Word2vec_5,Word2vec_6,Word2vec_7,Word2vec_8,Word2vec_9,...,Word2vec_290,Word2vec_291,Word2vec_292,Word2vec_293,Word2vec_294,Word2vec_295,Word2vec_296,Word2vec_297,Word2vec_298,Word2vec_299
0,-0.0389,0.0461,-0.0325,0.0007,-0.0464,-0.0107,0.1132,-0.1115,0.1225,0.0791,...,-0.0428,0.0826,-0.0809,-0.0216,-0.0228,0.0115,0.0100,-0.0240,-0.0811,-0.0210
1,-0.0248,0.0418,0.0107,-0.0078,-0.0484,-0.0242,0.0367,-0.0591,0.0857,0.0545,...,-0.0258,0.0576,-0.1260,0.0144,-0.0145,-0.0432,-0.1008,-0.0719,0.0223,-0.0430
2,-0.0357,0.0737,0.0062,0.0130,-0.0658,0.0373,-0.0165,-0.0890,0.0177,0.0333,...,-0.0326,0.0782,-0.0590,0.0027,0.0000,-0.0219,-0.1034,-0.0347,0.0073,-0.0010
3,0.0154,-0.0132,-0.0564,-0.0045,-0.1166,-0.0100,-0.0500,-0.1157,0.0740,0.0830,...,-0.0828,0.0362,-0.0542,0.0206,-0.0722,-0.0420,-0.1186,-0.0327,0.0566,0.0013
4,0.0405,0.0423,0.0511,-0.0112,-0.0855,0.0037,0.1200,-0.0999,0.1327,0.1117,...,-0.0617,0.0570,-0.0939,0.0174,-0.0134,-0.0347,0.0015,-0.0399,-0.0435,-0.0253

In [569]:
W2Vec_Data_test.head()

,Word2vec_0,Word2vec_1,Word2vec_2,Word2vec_3,Word2vec_4,Word2vec_5,Word2vec_6,Word2vec_7,Word2vec_8,Word2vec_9,...,Word2vec_290,Word2vec_291,Word2vec_292,Word2vec_293,Word2vec_294,Word2vec_295,Word2vec_296,Word2vec_297,Word2vec_298,Word2vec_299
0,-0.0224,0.0097,0.0366,0.0703,-0.0811,-0.0011,0.0285,-0.0886,0.0913,0.0646,...,-0.0071,0.0465,-0.0472,0.0495,-0.0082,-0.0025,-0.0031,-0.0278,-0.0715,-0.0265
1,-0.0134,0.0514,-0.0236,0.0503,-0.1160,-0.0236,0.0536,-0.1049,0.0687,0.0651,...,-0.0321,0.0561,-0.1170,0.0134,-0.0415,-0.0278,0.0023,-0.0106,-0.0183,-0.0489
2,0.0290,0.0119,0.0060,-0.0184,-0.1194,0.0163,0.0909,-0.1275,0.0398,0.0038,...,0.0057,0.1070,-0.0471,0.0509,0.0124,-0.0400,-0.0232,0.0038,-0.0473,-0.0219
3,-0.0129,0.0024,0.0409,0.1106,-0.0532,-0.0104,0.0598,-0.1222,0.0934,0.1503,...,-0.0272,-0.0610,-0.0059,0.0340,-0.0962,0.0453,-0.0034,0.0839,0.1053,-0.0908
4,0.0384,0.0092,0.0276,0.0308,-0.1075,-0.0074,0.0733,-0.1233,0.0524,0.0138,...,-0.0511,0.0617,-0.0995,0.0490,-0.0089,-0.0495,0.0448,-0.0103,-0.0655,0.0057

In [571]:
W2Vec_Data_train.shape

(1155, 300)

In [573]:
W2Vec_Data_test.shape

(105, 300)

In [575]:
final_dataset_train= df_train1[['Accident Level']].join(W2Vec_Data_train.reset_index(drop=True))

In [577]:
final_dataset_train.head()

,Accident Level,Word2vec_0,Word2vec_1,Word2vec_2,Word2vec_3,Word2vec_4,Word2vec_5,Word2vec_6,Word2vec_7,Word2vec_8,...,Word2vec_290,Word2vec_291,Word2vec_292,Word2vec_293,Word2vec_294,Word2vec_295,Word2vec_296,Word2vec_297,Word2vec_298,Word2vec_299
0,3,-0.0389,0.0461,-0.0325,0.0007,-0.0464,-0.0107,0.1132,-0.1115,0.1225,...,-0.0428,0.0826,-0.0809,-0.0216,-0.0228,0.0115,0.0100,-0.0240,-0.0811,-0.0210
1,1,-0.0248,0.0418,0.0107,-0.0078,-0.0484,-0.0242,0.0367,-0.0591,0.0857,...,-0.0258,0.0576,-0.1260,0.0144,-0.0145,-0.0432,-0.1008,-0.0719,0.0223,-0.0430
2,3,-0.0357,0.0737,0.0062,0.0130,-0.0658,0.0373,-0.0165,-0.0890,0.0177,...,-0.0326,0.0782,-0.0590,0.0027,0.0000,-0.0219,-0.1034,-0.0347,0.0073,-0.0010
3,1,0.0154,-0.0132,-0.0564,-0.0045,-0.1166,-0.0100,-0.0500,-0.1157,0.0740,...,-0.0828,0.0362,-0.0542,0.0206,-0.0722,-0.0420,-0.1186,-0.0327,0.0566,0.0013
4,1,0.0405,0.0423,0.0511,-0.0112,-0.0855,0.0037,0.1200,-0.0999,0.1327,...,-0.0617,0.0570,-0.0939,0.0174,-0.0134,-0.0347,0.0015,-0.0399,-0.0435,-0.0253

In [579]:
final_dataset_test= df_test1[['Accident Level']].join(W2Vec_Data_test.reset_index(drop=True))

In [581]:
final_dataset_test.head()

,Accident Level,Word2vec_0,Word2vec_1,Word2vec_2,Word2vec_3,Word2vec_4,Word2vec_5,Word2vec_6,Word2vec_7,Word2vec_8,...,Word2vec_290,Word2vec_291,Word2vec_292,Word2vec_293,Word2vec_294,Word2vec_295,Word2vec_296,Word2vec_297,Word2vec_298,Word2vec_299
0,1,-0.0224,0.0097,0.0366,0.0703,-0.0811,-0.0011,0.0285,-0.0886,0.0913,...,-0.0071,0.0465,-0.0472,0.0495,-0.0082,-0.0025,-0.0031,-0.0278,-0.0715,-0.0265
1,3,-0.0134,0.0514,-0.0236,0.0503,-0.1160,-0.0236,0.0536,-0.1049,0.0687,...,-0.0321,0.0561,-0.1170,0.0134,-0.0415,-0.0278,0.0023,-0.0106,-0.0183,-0.0489
2,1,0.0290,0.0119,0.0060,-0.0184,-0.1194,0.0163,0.0909,-0.1275,0.0398,...,0.0057,0.1070,-0.0471,0.0509,0.0124,-0.0400,-0.0232,0.0038,-0.0473,-0.0219
3,1,-0.0129,0.0024,0.0409,0.1106,-0.0532,-0.0104,0.0598,-0.1222,0.0934,...,-0.0272,-0.0610,-0.0059,0.0340,-0.0962,0.0453,-0.0034,0.0839,0.1053,-0.0908
4,2,0.0384,0.0092,0.0276,0.0308,-0.1075,-0.0074,0.0733,-0.1233,0.0524,...,-0.0511,0.0617,-0.0995,0.0490,-0.0089,-0.0495,0.0448,-0.0103,-0.0655,0.0057

In [583]:
final_dataset_test.shape

(105, 301)

In [585]:
final_dataset_train.to_csv("nlp_chatbot_word2vec_train.csv", index=False,header=True)

In [613]:
final_dataset_test.to_csv("nlp_chatbot_word2vec_test.csv", index=False,header=True)

In [591]:
#TF-IDF

In [593]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_df_train = pd.DataFrame()
for i in [1,2]:
    tfidf = TfidfVectorizer(max_features=50, stop_words='english',use_idf=True, ngram_range=(i,i))
    X = tfidf.fit_transform(df_train1['Description_WL']).toarray()
    tfs = pd.DataFrame(X, columns=["TFIDF_" + n for n in tfidf.get_feature_names_out()])
    tfidf_df_train = pd.concat([tfidf_df_train.reset_index(drop=True), tfs.reset_index(drop=True)], axis=1)

tfidf_df_train.head(5)

,TFIDF_accident,TFIDF_approximately,TFIDF_area,TFIDF_attempt,TFIDF_attention,TFIDF_belt,TFIDF_bruise,TFIDF_cause,TFIDF_conveyor,TFIDF_employee,...,TFIDF_routine inspection,TFIDF_routine maintenance,TFIDF_severe burn,TFIDF_severe injuries,TFIDF_severe lacerations,TFIDF_strike leave,TFIDF_sudden release,TFIDF_suffer severe,TFIDF_th routine,TFIDF_time accident
0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2922,0.0000,0.4530,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,0.3141,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
2,0.0000,0.0000,0.3543,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.3319,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1847,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [595]:
final_dataset_tfidf_train= df_train1[['Accident Level']].join(tfidf_df_train.reset_index(drop=True))

In [597]:
final_dataset_tfidf_train.to_csv("nlp_chatbot_tfidf_train.csv", index=False,header=True)

In [599]:
final_dataset_tfidf_train.shape

(1155, 101)

In [601]:
tfidf_df_test = pd.DataFrame()
X = tfidf.transform(df_test1['Description_WL']).toarray()
tfs = pd.DataFrame(X, columns=["TFIDF_" + n for n in tfidf.get_feature_names_out()])
tfidf_df_test = pd.concat([tfidf_df_test.reset_index(drop=True), tfs.reset_index(drop=True)], axis=1)
tfidf_df_test.head(5)

,TFIDF_approximately hours,TFIDF_approximately meter,TFIDF_attempt clear,TFIDF_attempt loosen,TFIDF_balance fall,TFIDF_belt employee,TFIDF_cause injury,TFIDF_cause lose,TFIDF_cause severe,TFIDF_concrete floor,...,TFIDF_routine inspection,TFIDF_routine maintenance,TFIDF_severe burn,TFIDF_severe injuries,TFIDF_severe lacerations,TFIDF_strike leave,TFIDF_sudden release,TFIDF_suffer severe,TFIDF_th routine,TFIDF_time accident
0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.7718,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [603]:
tfidf_df_test.shape

(105, 50)

In [605]:
final_dataset_tfidf_test= df_test1[['Accident Level']].join(tfidf_df_test.reset_index(drop=True))

In [607]:
final_dataset_tfidf_test.to_csv("nlp_chatbot_tfidf_test.csv", index=False,header=True)

In [609]:
final_dataset_tfidf_test.shape

(105, 51)

In [611]:
final_dataset_tfidf_test.head()

,Accident Level,TFIDF_approximately hours,TFIDF_approximately meter,TFIDF_attempt clear,TFIDF_attempt loosen,TFIDF_balance fall,TFIDF_belt employee,TFIDF_cause injury,TFIDF_cause lose,TFIDF_cause severe,...,TFIDF_routine inspection,TFIDF_routine maintenance,TFIDF_severe burn,TFIDF_severe injuries,TFIDF_severe lacerations,TFIDF_strike leave,TFIDF_sudden release,TFIDF_suffer severe,TFIDF_th routine,TFIDF_time accident
0,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,3,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.7718,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,1,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000