In [53]:
# Library to interact with the OS
import os

# Libraries for reading and manipulating data
import numpy as np
import pandas as pd

# Libraries for data visualization
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

%matplotlib inline
pd.set_option('display.float_format', lambda x: '%.4f' % x)

In [55]:
df_train=pd.read_csv('augmented_train.csv')

In [57]:
df_train.head(2)

,Potential Accident Level,Gender,Country_Country_01,Country_Country_02,Country_Country_03,Local_Local_01,Local_Local_02,Local_Local_03,Local_Local_04,Local_Local_05,...,Critical Risk_Projection/Burning,Critical Risk_Projection/Choco,Critical Risk_Projection/Manual Tools,Critical Risk_Suspended Loads,Critical Risk_Traffic,Critical Risk_Vehicles and Mobile Equipment,Critical Risk_Venomous Animals,Critical Risk_remains of choco,Description,Accident Level
0,4,0,0,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,By manually moving a steel cabinet for disposa...,3
1,4,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,Once the mooring of the faneles in the detonat...,1

In [59]:
df_test=pd.read_csv('augmented_test.csv')

In [61]:
df_test.head(2)

,Potential Accident Level,Gender,Description,Country_Country_01,Country_Country_02,Country_Country_03,Local_Local_01,Local_Local_02,Local_Local_03,Local_Local_04,...,Critical Risk_Projection of fragments,Critical Risk_Projection/Burning,Critical Risk_Projection/Choco,Critical Risk_Projection/Manual Tools,Critical Risk_Suspended Loads,Critical Risk_Traffic,Critical Risk_Vehicles and Mobile Equipment,Critical Risk_Venomous Animals,Critical Risk_remains of choco,0
0,1.0000,0.0000,On 02/03/17 during the soil sampling in the re...,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,NaN
1,4.0000,0.0000,During execution of drilling on the target - B...,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN

In [63]:
df_test.columns

Index(['Potential Accident Level', 'Gender', 'Description',
       'Country_Country_01', 'Country_Country_02', 'Country_Country_03',
       'Local_Local_01', 'Local_Local_02', 'Local_Local_03', 'Local_Local_04',
       'Local_Local_05', 'Local_Local_06', 'Local_Local_07', 'Local_Local_08',
       'Local_Local_09', 'Local_Local_10', 'Local_Local_11', 'Local_Local_12',
       'Industry Sector_Metals', 'Industry Sector_Mining',
       'Industry Sector_Others', 'Employee or Third Party_Employee',
       'Employee or Third Party_Third Party',
       'Employee or Third Party_Third Party (Remote)',
       'Critical Risk_\nNot applicable', 'Critical Risk_Bees',
       'Critical Risk_Blocking and isolation of energies',
       'Critical Risk_Burn', 'Critical Risk_Chemical substances',
       'Critical Risk_Confined space', 'Critical Risk_Cut',
       'Critical Risk_Electrical Shock',
       'Critical Risk_Electrical installation', 'Critical Risk_Fall',
       'Critical Risk_Fall prevention',
       'Critical Risk_Fall prevention (same level)',
       'Critical Risk_Individual protection equipment',
       'Critical Risk_Liquid Metal', 'Critical Risk_Machine Protection',
       'Critical Risk_Manual Tools', 'Critical Risk_Others',
       'Critical Risk_Plates', 'Critical Risk_Poll',
       'Critical Risk_Power lock', 'Critical Risk_Pressed',
       'Critical Risk_Pressurized Systems',
       'Critical Risk_Pressurized Systems / Chemical Substances',
       'Critical Risk_Projection', 'Critical Risk_Projection of fragments',
       'Critical Risk_Projection/Burning', 'Critical Risk_Projection/Choco',
       'Critical Risk_Projection/Manual Tools',
       'Critical Risk_Suspended Loads', 'Critical Risk_Traffic',
       'Critical Risk_Vehicles and Mobile Equipment',
       'Critical Risk_Venomous Animals', 'Critical Risk_remains of choco',
       '0'],
      dtype='object')

In [65]:
df_test.drop('0',inplace=True,axis=1)

In [67]:
df_test.head()

,Potential Accident Level,Gender,Description,Country_Country_01,Country_Country_02,Country_Country_03,Local_Local_01,Local_Local_02,Local_Local_03,Local_Local_04,...,Critical Risk_Projection,Critical Risk_Projection of fragments,Critical Risk_Projection/Burning,Critical Risk_Projection/Choco,Critical Risk_Projection/Manual Tools,Critical Risk_Suspended Loads,Critical Risk_Traffic,Critical Risk_Vehicles and Mobile Equipment,Critical Risk_Venomous Animals,Critical Risk_remains of choco
0,1.0000,0.0000,On 02/03/17 during the soil sampling in the re...,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000
1,4.0000,0.0000,During execution of drilling on the target - B...,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,3.0000,0.0000,"The operator was in the center (Demag IV), per...",0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,4.0000,0.0000,The employee was transiting toward the cadmium...,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,4.0000,0.0000,"Being 12:20 hours Approximately, in circumstan...",1.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [73]:
# to use regular expressions for manipulating text data
import re

# to load the natural language toolkit
import nltk
nltk.download('stopwords')    # loading the stopwords
nltk.download('wordnet')  

# to remove common stop words
from nltk.corpus import stopwords

# to perform stemming
from nltk.stem.porter import PorterStemmer

# to create Bag of Words
from sklearn.feature_extraction.text import CountVectorizer

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [101]:
# Removing non-alphanumeric chars
df_train['Description_T'] = df_train['Description'].apply(lambda x: ''.join(re.sub('[^A-Za-z0-9]+', ' ', str(x))))
df_test['Description_T'] = df_test['Description'].apply(lambda x: ''.join(re.sub('[^A-Za-z0-9]+', ' ', str(x))))

In [103]:
#removing digits
df_train['Description_T'] = df_train['Description_T'].apply(lambda x: ''.join(re.sub(r'\d+',' ', str(x))))
df_test['Description_T'] = df_test['Description_T'].apply(lambda x: ''.join(re.sub(r'\d+',' ', str(x))))

In [105]:
# To lowercase
df_train['Description_T'] = df_train['Description_T'].apply(lambda x: str(x).lower())
df_test['Description_T'] = df_test['Description_T'].apply(lambda x: str(x).lower())

In [107]:
df_train['Description_T'] = df_train['Description_T'].str.strip()
df_test['Description_T'] = df_test['Description_T'].str.strip()

In [109]:
# Stopword removal
df_train['Description_T'] = df_train['Description_T'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))

# Stopword removal
df_test['Description_T'] = df_test['Description_T'].apply(lambda x: ' '.join([word for word in x.split() if word not in stopwords.words('english')]))

In [111]:
df_train.loc[0:10, ['Description', 'Description_T']]

,Description,Description_T
0,By manually moving a steel cabinet for disposa...,manually moving steel cabinet disposal help an...
1,Once the mooring of the faneles in the detonat...,mooring faneles detonating cord completed inju...
2,When performing cleaning activity of the area ...,performing cleaning activity area near tc grin...
3,The technician was doing the magnetometric sur...,technician magnetometric survey stepped thorn ...
4,The operator cleaned with spatula spear throug...,operator cleaned spatula spear one windows boi...
5,"On 02/25/2017 at 13:05 p.m., when assisting wi...",p assisting gps magnetometric collaborator gil...
6,"On 05/02/2017, at 10:40 p.m., when performing ...",p performing geological mapping activity geolo...
7,"In phase III of the concentrator plant, the ma...",phase iii concentrator plant maintenance perso...
8,"While preparing to mount polypropylene tubing,...",preparing mount polypropylene tubing employee ...
9,After the welder completed the welding work to...,welder completed welding work reinforce forms ...
10,The technician Operator when heading towards t...,technician operator heading towards zone lifti...

In [115]:
df_test.loc[0:10, ['Description', 'Description_T']]

,Description,Description_T
0,On 02/03/17 during the soil sampling in the re...,soil sampling region sta employees rafael dani...
1,During execution of drilling on the target - B...,execution drilling target bolt brjcldd made co...
2,"The operator was in the center (Demag IV), per...",operator center demag iv performing maintenanc...
3,The employee was transiting toward the cadmium...,employee transiting toward cadmium factory nea...
4,"Being 12:20 hours Approximately, in circumstan...",hours approximately circumstances administrati...
5,"At Rp 050 of level 1620, in circumstances wher...",rp level circumstances workers company perform...
6,When observing the pulp overflow of the overfl...,observing pulp overflow overflow reception dra...
7,During the execution of the soil sampling task...,execution soil sampling task potions area arou...
8,In moments that the truck of transport of pers...,moments truck transport personnel company mcei...
9,Employee moved toward the structure of post 10...,employee moved toward structure post came step...
10,The employees MÃ¡rcio and SÃ©rgio performed the ...,employees rcio rgio performed pump pipe cleari...

In [119]:
nltk.download('punkt')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
df_train['Description_WL'] = df_train.apply(lambda row: nltk.word_tokenize(row['Description_T']), axis=1)
def lemmatize_list(words):
    new_words = []
    for word in words:
      new_words.append(lemmatizer.lemmatize(word, pos='v'))
    return ' '.join(new_words)
df_train['Description_WL'] = df_train.apply(lambda x: lemmatize_list(x['Description_WL']), axis=1)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [121]:
df_train.loc[0:10, ['Description', 'Description_WL']]

,Description,Description_WL
0,By manually moving a steel cabinet for disposa...,manually move steel cabinet disposal help anot...
1,Once the mooring of the faneles in the detonat...,moor faneles detonate cord complete injure per...
2,When performing cleaning activity of the area ...,perform clean activity area near tc grind empl...
3,The technician was doing the magnetometric sur...,technician magnetometric survey step thorn rea...
4,The operator cleaned with spatula spear throug...,operator clean spatula spear one windows boile...
5,"On 02/25/2017 at 13:05 p.m., when assisting wi...",p assist gps magnetometric collaborator gilv n...
6,"On 05/02/2017, at 10:40 p.m., when performing ...",p perform geological map activity geologist ma...
7,"In phase III of the concentrator plant, the ma...",phase iii concentrator plant maintenance perso...
8,"While preparing to mount polypropylene tubing,...",prepare mount polypropylene tube employee pull...
9,After the welder completed the welding work to...,welder complete weld work reinforce form deepe...
10,The technician Operator when heading towards t...,technician operator head towards zone lift con...

In [123]:
nltk.download('punkt')
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
df_test['Description_WL'] = df_test.apply(lambda row: nltk.word_tokenize(row['Description_T']), axis=1)
def lemmatize_list(words):
    new_words = []
    for word in words:
      new_words.append(lemmatizer.lemmatize(word, pos='v'))
    return ' '.join(new_words)
df_test['Description_WL'] = df_test.apply(lambda x: lemmatize_list(x['Description_WL']), axis=1)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\nehag\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [125]:
df_test.loc[0:10, ['Description', 'Description_WL']]

,Description,Description_WL
0,On 02/03/17 during the soil sampling in the re...,soil sample region sta employees rafael danill...
1,During execution of drilling on the target - B...,execution drill target bolt brjcldd make compa...
2,"The operator was in the center (Demag IV), per...",operator center demag iv perform maintenance t...
3,The employee was transiting toward the cadmium...,employee transit toward cadmium factory near t...
4,"Being 12:20 hours Approximately, in circumstan...",hours approximately circumstances administrati...
5,"At Rp 050 of level 1620, in circumstances wher...",rp level circumstances workers company perform...
6,When observing the pulp overflow of the overfl...,observe pulp overflow overflow reception drawe...
7,During the execution of the soil sampling task...,execution soil sample task potions area around...
8,In moments that the truck of transport of pers...,moments truck transport personnel company mcei...
9,Employee moved toward the structure of post 10...,employee move toward structure post come step ...
10,The employees MÃ¡rcio and SÃ©rgio performed the ...,employees rcio rgio perform pump pipe clear ac...

In [249]:
df_train1=df_train.copy()
df_test1=df_test.copy()

In [129]:
import gensim.downloader as api
wv = api.load('word2vec-google-news-300')

vec_king = wv['king']

In [251]:
# Count vectorization of text
from sklearn.feature_extraction.text import CountVectorizer
 
# Ticket Data
corpus = df_train1['Description_WL'].values
 
# Creating the vectorizer
vectorizer = CountVectorizer(stop_words='english')
 
# Converting the text to numeric data
X = vectorizer.fit_transform(corpus)
 
#print(vectorizer.get_feature_names())
 
# Preparing Data frame For machine learning
# Priority column acts as a target variable and other columns as predictors
CountVectorizedData_train=pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
print(CountVectorizedData_train.shape)
CountVectorizedData_train.head()

(1155, 3005)

,abb,abc,abdomen,able,abnormally,abrasion,abrasions,abrasive,abrupt,abruptly,...,yield,young,zaf,zamac,zaro,zero,zinc,zinco,zn,zone
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [253]:
WordsVocab_train=CountVectorizedData_train.columns[:]

In [255]:
def FunctionText2Vec_train(inpTextData):
    # Converting the text to numeric data
    X = vectorizer.transform(inpTextData)
    CountVecData=pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
    
    # Creating empty dataframe to hold sentences
    W2Vec_Data=pd.DataFrame()
    
    # Looping through each row for the data
    for i in range(CountVecData.shape[0]):
 
        # initiating a sentence with all zeros
        Sentence = np.zeros(300)
 
        # Looping thru each word in the sentence and if its present in 
        # the Word2Vec model then storing its vector
        for word in WordsVocab_train[CountVecData.iloc[i , :]>=1]:
            #print(word)
            if word in wv.key_to_index.keys():    
                Sentence=Sentence+wv[word]
        # Appending the sentence to the dataframe
        W2Vec_Data=W2Vec_Data.append(pd.DataFrame([Sentence], columns=['Word2vec_'+str(i) for i in range(300)]))
    return(W2Vec_Data)

In [257]:
W2Vec_Data_train=FunctionText2Vec_train(df_train1['Description_WL'])
 
# Checking the new representation for sentences
W2Vec_Data_train.shape

(1155, 300)

In [169]:
# Count vectorization of text
from sklearn.feature_extraction.text import CountVectorizer
 
# Ticket Data
corpus = df_test1['Description_WL'].values
 
# Creating the vectorizer
vectorizer = CountVectorizer(stop_words='english')
 
# Converting the text to numeric data
X = vectorizer.fit_transform(corpus)
 
#print(vectorizer.get_feature_names())
 
# Preparing Data frame For machine learning
# Priority column acts as a target variable and other columns as predictors
CountVectorizedData_test=pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
print(CountVectorizedData_test.shape)
CountVectorizedData_test.head()

(210, 1088)

,abratech,abrupt,abruptly,access,accident,accidentally,accommodate,accompany,accretion,accumulate,...,workshop,wrench,wrist,xxx,ydrs,yield,yolk,zaro,zinc,zn
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [171]:
WordsVocab_test=CountVectorizedData_test.columns[:]

In [173]:
def FunctionText2Vec_test(inpTextData):
    # Converting the text to numeric data
    X = vectorizer.transform(inpTextData)
    CountVecData=pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
    
    # Creating empty dataframe to hold sentences
    W2Vec_Data=pd.DataFrame()
    
    # Looping through each row for the data
    for i in range(CountVecData.shape[0]):
 
        # initiating a sentence with all zeros
        Sentence = np.zeros(300)
 
        # Looping thru each word in the sentence and if its present in 
        # the Word2Vec model then storing its vector
        for word in WordsVocab_test[CountVecData.iloc[i , :]>=1]:
            #print(word)
            if word in wv.key_to_index.keys():    
                Sentence=Sentence+wv[word]
        # Appending the sentence to the dataframe
        W2Vec_Data=W2Vec_Data.append(pd.DataFrame([Sentence], columns=['Word2vec_'+str(i) for i in range(300)]))
    return(W2Vec_Data)

In [175]:
W2Vec_Data_test=FunctionText2Vec_test(df_test1['Description_WL'])
 
# Checking the new representation for sentences
W2Vec_Data_test.shape

(210, 300)

In [177]:
final_dataset_train= df_train1[['Accident Level']].join(W2Vec_Data_train.reset_index(drop=True))

In [191]:
final_dataset_train.to_csv("nlp_chatbot_word2vec_train.csv", index=False,header=True)

In [193]:
W2Vec_Data_test.to_csv("nlp_chatbot_word2vec_test.csv", index=False,header=True)

In [185]:
#glove

In [187]:
# Converting the Stanford GloVe model vector format to word2vec
from gensim.scripts.glove2word2vec import glove2word2vec
from gensim.models import KeyedVectors
glove_input_file = 'glove.6B.100d.txt'
word2vec_output_file = 'glove.6B.100d.txt.word2vec'
glove2word2vec(glove_input_file, word2vec_output_file)

(400000, 100)

In [195]:
# load the Stanford GloVe model
filename = 'glove.6B.100d.txt.word2vec'
glove_model = KeyedVectors.load_word2vec_format(filename, binary=False)

In [196]:
# Checking the size of the vocabulary
print("Length of the vocabulary is", len(glove_model.index_to_key))

Length of the vocabulary is 400000

In [199]:
# Checking the word embedding of a random word
word = "drill"
glove_model[word]

array([-0.35765  ,  0.81467  , -0.2346   , -0.33073  , -0.55697  ,
       -0.91257  ,  0.13386  ,  0.89648  , -0.68417  ,  0.8944   ,
        0.33198  ,  0.52635  ,  0.54153  ,  0.38754  , -0.38877  ,
       -0.17014  , -0.24252  ,  0.39321  , -0.58885  , -0.44848  ,
        0.50495  ,  0.017128 , -0.040326 , -0.30586  , -0.024022 ,
        0.41875  , -1.1461   ,  0.8086   ,  0.12388  ,  0.21747  ,
       -0.94692  , -0.20167  ,  0.35933  ,  0.15633  , -0.039052 ,
       -0.46565  , -1.2225   , -0.48241  ,  0.65021  , -0.4558   ,
       -0.18787  , -0.05471  , -0.6474   , -0.25599  , -0.16758  ,
       -0.18455  , -0.40177  ,  0.22248  , -0.1685   , -0.60159  ,
       -0.54771  ,  0.37457  , -0.21604  ,  0.77251  , -0.32279  ,
       -0.94642  , -0.081026 , -0.87158  ,  1.3124   ,  1.0501   ,
        0.095171 ,  0.46109  ,  0.91197  ,  0.39826  ,  0.032378 ,
        0.25852  , -0.12024  , -0.29043  , -0.010148 ,  0.22901  ,
        0.26109  , -0.18566  ,  0.030369 ,  0.11884  ,  0.056801 ,
        0.60609  ,  0.55356  ,  0.18386  ,  0.082414 ,  0.2639   ,
        0.69594  , -0.54589  , -0.011881 , -0.16833  , -0.9914   ,
        0.11812  ,  1.1473   ,  0.4323   ,  0.91819  ,  0.0019491,
       -0.095731 ,  0.16852  , -0.55276  ,  0.10321  ,  0.942    ,
        0.012303 , -0.59046  , -0.38823  , -0.040919 ,  0.42908  ],
      dtype=float32)

In [201]:
# Retrieving the words present in the GloVe model's vocabulary
glove_words = glove_model.index_to_key

# Creating a dictionary of words and their corresponding vectors
glove_word_vector_dict = dict(zip(glove_model.index_to_key,list(glove_model.vectors)))

In [203]:
vec_size=100

In [205]:
def average_vectorizer_GloVe(doc):
    # Initializing a feature vector for the sentence
    feature_vector = np.zeros((vec_size,), dtype="float64")

    # Creating a list of words in the sentence that are present in the model vocabulary
    words_in_vocab = [word for word in doc.split() if word in glove_words]

    # adding the vector representations of the words
    for word in words_in_vocab:
        feature_vector += np.array(glove_word_vector_dict[word])

    # Dividing by the number of words to get the average vector
    if len(words_in_vocab) != 0:
        feature_vector /= len(words_in_vocab)

    return feature_vector

In [207]:
# creating a dataframe of the vectorized documents
df_train_Glove = pd.DataFrame(df_train1['Description_WL'].apply(average_vectorizer_GloVe).tolist(), columns=['Glove_'+str(i) for i in range(vec_size)])
df_train_Glove.head()

,Glove_0,Glove_1,Glove_2,Glove_3,Glove_4,Glove_5,Glove_6,Glove_7,Glove_8,Glove_9,...,Glove_90,Glove_91,Glove_92,Glove_93,Glove_94,Glove_95,Glove_96,Glove_97,Glove_98,Glove_99
0,-0.2623,-0.0841,0.1282,-0.1997,-0.0630,-0.0496,-0.2303,0.1156,0.1853,0.1863,...,0.1082,-0.1110,-0.0686,0.1333,-0.0839,0.1923,0.3424,-0.2759,0.5752,-0.1874
1,-0.2027,0.1678,0.0350,-0.0604,-0.1545,0.0998,-0.0327,0.1934,-0.1007,0.2192,...,-0.0453,0.2017,0.0147,0.0042,-0.0336,0.0225,-0.0656,-0.1288,0.4219,-0.1941
2,-0.4038,0.3504,-0.0543,0.0028,-0.2617,0.1594,-0.1096,0.1454,-0.1383,0.1892,...,-0.1371,0.2488,0.0567,0.0614,-0.0335,0.0448,-0.1588,-0.1819,0.5797,-0.1138
3,-0.1460,0.0384,0.1180,0.0200,-0.3475,-0.2282,-0.0424,0.1417,-0.0790,0.0452,...,-0.0822,-0.0289,-0.0698,0.1573,-0.1465,0.0872,0.2163,-0.1254,0.2030,0.1634
4,-0.2310,0.1610,0.0229,-0.2509,-0.1190,0.1436,-0.0991,0.1991,0.0684,0.2025,...,-0.0414,-0.0326,0.0487,-0.0031,0.0291,0.0168,0.0638,-0.1638,0.4409,-0.1961

In [209]:
df_train_Glove.shape

(1155, 100)

In [213]:
final_dataset_glove_train= df_train1[['Accident Level']].join(df_train_Glove.reset_index(drop=True))

In [215]:
final_dataset_glove_train.to_csv("nlp_chatbot_glove_train.csv", index=False,header=True)

In [217]:
# creating a dataframe of the vectorized documents
df_test_Glove = pd.DataFrame(df_test1['Description_WL'].apply(average_vectorizer_GloVe).tolist(), columns=['Glove_'+str(i) for i in range(vec_size)])
df_test_Glove.head()

,Glove_0,Glove_1,Glove_2,Glove_3,Glove_4,Glove_5,Glove_6,Glove_7,Glove_8,Glove_9,...,Glove_90,Glove_91,Glove_92,Glove_93,Glove_94,Glove_95,Glove_96,Glove_97,Glove_98,Glove_99
0,-0.2038,0.0308,0.1292,-0.2621,-0.2052,0.1716,-0.0224,0.2435,-0.0540,0.1468,...,0.0275,-0.0341,0.0555,0.0106,-0.2028,0.1686,0.0049,-0.1679,0.3551,-0.0071
1,-0.1566,0.0534,-0.0504,-0.1828,-0.0559,-0.1275,-0.1065,0.1858,-0.0243,0.1024,...,-0.1016,0.0170,-0.1687,0.0072,-0.0843,-0.1431,-0.0242,-0.2812,0.4429,-0.0124
2,-0.3406,0.0817,0.0107,-0.0550,-0.0234,-0.0894,-0.1490,0.1673,0.0645,0.2124,...,0.0446,-0.0131,0.0044,-0.1081,-0.0302,0.0266,0.0457,-0.2696,0.5144,-0.0667
3,-0.0848,0.1955,0.0782,0.0013,0.0383,-0.3407,-0.0659,0.0959,0.0179,0.2631,...,0.0383,-0.2204,-0.3644,0.1420,-0.2120,0.0125,-0.0540,-0.0064,0.5232,-0.0805
4,-0.2000,0.0687,0.1034,-0.0566,-0.0721,0.2790,-0.1755,0.1450,0.0065,-0.0484,...,-0.2636,-0.0324,-0.0332,0.0336,-0.3325,-0.1340,0.1489,-0.1896,0.6406,-0.0262

In [219]:
df_test_Glove.shape

(210, 100)

In [221]:
df_test_Glove.to_csv("nlp_chatbot_glove_test.csv", index=False,header=True)

In [225]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_df_train = pd.DataFrame()
for i in [1,2]:
    tfidf = TfidfVectorizer(max_features=50, stop_words='english',use_idf=True, ngram_range=(i,i))
    X = tfidf.fit_transform(df_train1['Description_WL']).toarray()
    tfs = pd.DataFrame(X, columns=["TFIDF_" + n for n in tfidf.get_feature_names_out()])
    tfidf_df_train = pd.concat([tfidf_df_train.reset_index(drop=True), tfs.reset_index(drop=True)], axis=1)

tfidf_df_train.head(5)

,TFIDF_accident,TFIDF_approximately,TFIDF_area,TFIDF_attempt,TFIDF_attention,TFIDF_belt,TFIDF_bruise,TFIDF_cause,TFIDF_conveyor,TFIDF_employee,...,TFIDF_routine inspection,TFIDF_routine maintenance,TFIDF_severe burn,TFIDF_severe injuries,TFIDF_severe lacerations,TFIDF_strike leave,TFIDF_sudden release,TFIDF_suffer severe,TFIDF_th routine,TFIDF_time accident
0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.2922,0.0000,0.4530,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,0.3141,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000
2,0.0000,0.0000,0.3543,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.3319,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.1847,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [227]:
final_dataset_tfidf_train= df_train1[['Accident Level']].join(tfidf_df_train.reset_index(drop=True))

In [229]:
final_dataset_tfidf_train.to_csv("nlp_chatbot_tfidf_train.csv", index=False,header=True)

In [241]:
tfidf_df_test = pd.DataFrame()
X = tfidf.fit_transform(df_test1['Description_WL']).toarray()
tfs = pd.DataFrame(X, columns=["TFIDF_" + n for n in tfidf.get_feature_names_out()])
tfidf_df_test = pd.concat([tfidf_df_test.reset_index(drop=True), tfs.reset_index(drop=True)], axis=1)
tfidf_df_test.head(5)

,TFIDF_accident employee,TFIDF_activity employee,TFIDF_allergic reaction,TFIDF_blunt cut,TFIDF_cause blunt,TFIDF_cause cut,TFIDF_cause injury,TFIDF_circumstances operator,TFIDF_cut position,TFIDF_da silva,...,TFIDF_right hand,TFIDF_rotation unit,TFIDF_steel plate,TFIDF_support mesh,TFIDF_throw floor,TFIDF_time accident,TFIDF_time event,TFIDF_twist leave,TFIDF_wear safety,TFIDF_work area
0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,0.0000,0.0000,0.0000,0.0000,0.0000,0.5576,0.4208,0.0000,0.0000,0.5838,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,0.0000,0.0000,0.0000,0.0000,0.3575,0.0000,0.0000,0.0000,0.0000,...,0.5305,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [243]:
tfidf_df_test.shape

(210, 50)

In [245]:
tfidf_df_test.to_csv("nlp_chatbot_tfidf_test_new.csv", index=False,header=True)

In [259]:
tfidf_df_test.head()

,TFIDF_accident employee,TFIDF_activity employee,TFIDF_allergic reaction,TFIDF_blunt cut,TFIDF_cause blunt,TFIDF_cause cut,TFIDF_cause injury,TFIDF_circumstances operator,TFIDF_cut position,TFIDF_da silva,...,TFIDF_right hand,TFIDF_rotation unit,TFIDF_steel plate,TFIDF_support mesh,TFIDF_throw floor,TFIDF_time accident,TFIDF_time event,TFIDF_twist leave,TFIDF_wear safety,TFIDF_work area
0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,0.0000,0.0000,0.0000,0.0000,0.0000,0.5576,0.4208,0.0000,0.0000,0.5838,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
3,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
4,0.0000,0.0000,0.0000,0.0000,0.0000,0.3575,0.0000,0.0000,0.0000,0.0000,...,0.5305,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000

In [261]:
tfidf_df_test.shape

(210, 50)